"""Cloud mode — Switch Discovery API."""

from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, Depends

from web.backend.auth.router import get_current_user
from web.backend.config import settings
from web.backend.core.env_parser import read_env
from web.backend.core.script_runner import run_script
from web.backend.models.schemas import (
    DeviceSelection,
    DiscoveryDevice,
    DiscoveryResults,
    JobStartResponse,
)

router = APIRouter(prefix="/api/v1/cloud/discovery", tags=["cloud-discovery"])

_SCRIPT = str(settings.cloud_admin_dir / "discoverswitches.sh")
_RESULTS = settings.cloud_admin_dir / "discovery_results.json"
_SELECTED = settings.cloud_admin_dir / "selected_upgrade.env"


@router.post("/start", response_model=JobStartResponse)
async def start_discovery(_user: str = Depends(get_current_user)):
    """Launch discoverswitches.sh and return job ID for progress tracking."""
    env_file = str(settings.cloud_admin_dir / "meraki_discovery.env")
    job = await run_script(
        _SCRIPT,
        args=[env_file],
        mode="cloud",
        category="discovery",
    )
    return JobStartResponse(job_id=job.job_id, status=job.status.value)


@router.get("/results", response_model=DiscoveryResults)
async def get_results(_user: str = Depends(get_current_user)):
    """Read discovery_results.json produced by the last discovery run."""
    if not _RESULTS.is_file():
        return DiscoveryResults(devices=[], total=0, eligible=0)

    try:
        raw = json.loads(_RESULTS.read_text())
    except Exception:
        return DiscoveryResults(devices=[], total=0, eligible=0)

    devices_list = raw if isinstance(raw, list) else []
    devices = []
    eligible = 0
    for d in devices_list:
        dev = DiscoveryDevice(
            ip=d.get("ip", ""),
            hostname=d.get("hostname", ""),
            pid=d.get("pid", ""),
            serial=d.get("serial", ""),
            ssh=d.get("ssh", False),
            login=d.get("login", False),
            blacklisted=d.get("blacklisted", False),
            backup_status=d.get("backup_status", ""),
            backup_path=d.get("backup_path", ""),
            uplink_type=d.get("uplink_type", ""),
        )
        devices.append(dev)
        if dev.ssh and dev.login and not dev.blacklisted:
            eligible += 1

    return DiscoveryResults(devices=devices, total=len(devices), eligible=eligible)


@router.post("/select")
async def select_devices(
    selection: DeviceSelection, _user: str = Depends(get_current_user)
):
    """Write selected IPs to selected_upgrade.env."""
    ips = selection.ips
    lines = [
        "# Auto-generated by CMDS2 Web UI",
        f'export UPGRADE_IPS="{" ".join(ips)}"',
        f"export UPGRADE_COUNT={len(ips)}",
        "",
    ]
    _SELECTED.write_text("\n".join(lines))

    # Also write selected_upgrade.json for scripts that expect it
    json_path = settings.cloud_admin_dir / "selected_upgrade.json"
    results_data = []
    if _RESULTS.is_file():
        try:
            all_devices = json.loads(_RESULTS.read_text())
            if isinstance(all_devices, list):
                results_data = [d for d in all_devices if d.get("ip") in ips]
        except Exception:
            pass
    json_path.write_text(json.dumps(results_data, indent=2))

    return {"selected": len(ips), "ips": ips}
