"""Read and write bash-style .env files used by CMDS2 scripts."""

from __future__ import annotations

import re
import shlex
from pathlib import Path

# Fields that must never be returned in plaintext to the frontend
_SENSITIVE_KEYS = {"MERAKI_API_KEY", "SSH_PASSWORD", "ENABLE_PASSWORD"}

_KV_RE = re.compile(
    r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$"
)


def read_env(path: Path) -> dict[str, str]:
    """Parse a bash-style env file into a dict.

    Handles: KEY=value, KEY="value", KEY='value', export KEY=value.
    Skips comments and blank lines.
    """
    result: dict[str, str] = {}
    if not path.is_file():
        return result
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = _KV_RE.match(line)
        if m:
            key = m.group(1)
            raw = m.group(2)
            # Strip surrounding quotes
            if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in ('"', "'"):
                raw = raw[1:-1]
            result[key] = raw
    return result


def read_env_masked(path: Path) -> dict[str, str]:
    """Read env file but mask sensitive values."""
    data = read_env(path)
    for k in _SENSITIVE_KEYS:
        if k in data and data[k]:
            v = data[k]
            data[k] = v[:4] + "****" + v[-4:] if len(v) > 8 else "****"
    return data


def _double_quote(value: str) -> str:
    """Escape a value for double-quoting in bash (matches setupwizard.sh style).

    shlex.quote() uses single-quotes which break round-trip when values
    contain single quotes.  The original scripts always use double-quoting,
    so we do the same:  escape \\ $ ` " ! and wrap in double quotes.
    """
    escaped = value.replace("\\", "\\\\")
    escaped = escaped.replace('"', '\\"')
    escaped = escaped.replace("$", "\\$")
    escaped = escaped.replace("`", "\\`")
    escaped = escaped.replace("!", "\\!")
    return f'"{escaped}"'


def write_env(path: Path, data: dict[str, str]):
    """Write a dict as a bash-sourceable env file."""
    lines = ["# Auto-generated by CMDS2 Web UI", ""]
    for key, value in data.items():
        lines.append(f"export {key}={_double_quote(value)}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
